# Generated by Django 4.2.24 on 2025-10-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_manage_users', 'Can manage all users'), ('can_manage_roles', 'Can manage roles'), ('can_manage_divisions', 'Can manage divisions'), ('can_upload_archives', 'Can upload new archives'), ('can_edit_own_archives', 'Can edit own division archives'), ('can_delete_own_archives', 'Can delete own division archives'), ('can_view_all_archives', 'Can view archives from all divisions'), ('can_manage_students', 'Can manage student data'), ('can_manage_wilayah', 'Can manage wilayah data'), ('can_manage_religions', 'Can manage religion data')],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['-created_at']},
        ),
    ]
