# Generated by Django 4.2.24 on 2025-10-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_masterpermission_alter_archive_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterpermission',
            options={'managed': False, 'permissions': [('can_manage_users', 'Can manage all users'), ('can_manage_roles', 'Can manage roles'), ('can_manage_divisions', 'Can manage divisions'), ('can_upload_archives', 'Can upload new archives'), ('can_edit_own_archives', 'Can edit own division archives'), ('can_delete_own_archives', 'Can delete own division archives'), ('can_view_all_archives', 'Can view archives from all divisions'), ('can_crud_students', 'Can create, read, update, delete student data'), ('can_crud_wilayah', 'Can create, read, update, delete wilayah data'), ('can_crud_religions', 'Can create, read, update, delete religion data')]},
        ),
    ]
