# Generated by Django 4.2.24 on 2025-10-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_masterpermission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('SD', 'Sekolah Dasar'), ('SMP', 'Sekolah Menengah Pertama'), ('SMA', 'Sekolah Menengah Atas'), ('D2', 'Diploma 2'), ('D3', 'Diploma 3'), ('D4', 'Diploma 4'), ('S1', 'Strata 1'), ('S2', 'Strata 2'), ('S3', 'Strata 3'), ('PROF', 'Profesor')], max_length=10, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='masterpermission',
            options={'managed': False, 'permissions': [('can_manage_users', 'Can manage all users'), ('can_manage_roles', 'Can manage roles'), ('can_manage_divisions', 'Can manage divisions'), ('can_upload_archives', 'Can upload new archives'), ('can_edit_own_archives', 'Can edit own division archives'), ('can_delete_own_archives', 'Can delete own division archives'), ('can_view_all_archives', 'Can view archives from all divisions'), ('can_crud_education', 'Can create, read, update, delete student data'), ('can_crud_wilayah', 'Can create, read, update, delete wilayah data'), ('can_crud_religions', 'Can create, read, update, delete religion data')]},
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
