# Generated by Django 4.2.24 on 2025-10-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_masterpermission_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterPermission',
        ),
        migrations.RemoveField(
            model_name='educationlevel',
            name='education_level',
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='name',
            field=models.CharField(default='Jenjang Pendidikan Baru', max_length=100),
        ),
    ]
