# Generated by Django 4.2.24 on 2025-10-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_masterpermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationlevel',
            name='name',
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='code',
            field=models.CharField(blank=True, choices=[('SD', 'Sekolah Dasar'), ('SMP', 'Sekolah Menengah Pertama'), ('SMA', 'Sekolah Menengah Atas'), ('D2', 'Diploma 2'), ('D3', 'Diploma 3'), ('D4', 'Diploma 4'), ('S1', 'Strata 1'), ('S2', 'Strata 2'), ('S3', 'Strata 3'), ('PROF', 'Profesor')], max_length=10, null=True, unique=True),
        ),
    ]
