# Generated by Django 4.2.24 on 2025-10-22 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_educationlevel_name_educationlevel_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
