# Generated by Django 4.2.24 on 2025-10-22 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('kode_dosen', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Kode Dosen')),
                ('nama_dosen', models.CharField(max_length=150, verbose_name='Nama Dosen')),
                ('nidn', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Nomor Induk Dosen Nasional')),
                ('nip', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='Nomor Induk Pegawai')),
                ('gelar_depan', models.CharField(blank=True, max_length=50, null=True)),
                ('gelar_belakang', models.CharField(blank=True, max_length=50, null=True)),
                ('jk', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('kode_unit', models.CharField(max_length=20, verbose_name='Kode Unit Kerja/Prodi')),
                ('status_aktif', models.CharField(default='Aktif', max_length=10, verbose_name='Status Keaktifan')),
                ('jabatan_fungsional', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jabatan Fungsional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dosen',
            },
        ),
        migrations.CreateModel(
            name='KonsentrasiUtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_konsentrasi', models.CharField(max_length=25, unique=True, verbose_name='Kode Konsentrasi')),
                ('nama_konsentrasi', models.CharField(max_length=100, verbose_name='Nama Konsentrasi')),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=15, unique=True, verbose_name='NIM')),
                ('nama_mahasiswa', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('tgl_lahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('tahun_masuk', models.IntegerField(verbose_name='Tahun Angkatan')),
                ('jk', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('judul_skripsi', models.CharField(blank=True, max_length=300, verbose_name='Judul Skripsi/Proposal')),
                ('konsentrasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.konsentrasiutama')),
            ],
            options={
                'verbose_name': 'Mahasiswa',
                'verbose_name_plural': 'Data Mahasiswa',
                'ordering': ['nim'],
            },
        ),
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(max_length=10, unique=True, verbose_name='Kode Program Studi')),
                ('nama_prodi', models.CharField(max_length=200, verbose_name='Nama Program Studi')),
            ],
            options={
                'verbose_name': 'Program Studi',
                'verbose_name_plural': 'Daftar Program Studi',
                'ordering': ['kode_prodi'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('catatan', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='proposals/')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosen_pembimbing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dosen')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='api.mahasiswa')),
            ],
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='prodi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.prodi'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='tempat_lahir',
            field=models.ForeignKey(blank=True, db_column='tempat_lahir', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wilayah'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dosen',
            name='konsentrasi',
            field=models.ManyToManyField(blank=True, to='api.konsentrasiutama'),
        ),
        migrations.CreateModel(
            name='Bimbingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dosen')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mahasiswa')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.proposal')),
            ],
            options={
                'unique_together': {('dosen', 'mahasiswa')},
            },
        ),
    ]
