# Generated by Django 4.2.24 on 2025-10-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dosen_konsentrasiutama_mahasiswa_prodi_proposal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodi',
            options={'ordering': ['code'], 'verbose_name': 'Program Studi', 'verbose_name_plural': 'Daftar Program Studi'},
        ),
        migrations.RenameField(
            model_name='konsentrasiutama',
            old_name='kode_konsentrasi',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='konsentrasiutama',
            old_name='nama_konsentrasi',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='prodi',
            old_name='kode_prodi',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='prodi',
            old_name='nama_prodi',
            new_name='name',
        ),
    ]
