# Generated by Django 4.2.24 on 2025-10-22 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_prodi_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosen',
            name='konsentrasi',
        ),
        migrations.AddField(
            model_name='dosen',
            name='konsentrasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.konsentrasiutama'),
        ),
    ]
