# Generated by Django 4.2.24 on 2025-10-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_dosen_konsentrasi_dosen_konsentrasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosen',
            name='kode_unit',
        ),
        migrations.AddField(
            model_name='dosen',
            name='prodi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.prodi'),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='tempat_lahir',
            field=models.ForeignKey(blank=True, db_column='tempat_lahir', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wilayah'),
        ),
    ]
