# Generated by Django 4.2.24 on 2025-10-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_dosen_kode_unit_dosen_prodi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='alamat',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alamat'),
        ),
    ]
