# Generated by Django 4.2.24 on 2025-10-30 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_mahasiswa_alamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
