# Generated by Django 4.2.24 on 2025-10-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_mahasiswa_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='status_aktif',
            field=models.CharField(default='Aktif', max_length=30, verbose_name='Status Keaktifan'),
        ),
    ]
