# Generated by Django 4.2.24 on 2025-11-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_dosen_status_aktif'),
    ]

    operations = [
        migrations.AddField(
            model_name='konsentrasiutama',
            name='prodi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.prodi'),
        ),
    ]
