import { User, Division, Archive } from '../types';

export const divisions: Division[] = [
  {
    id: '1',
    name: 'IT',
    description: 'Information Technology Division',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Finance',
    description: 'Finance and Accounting Division',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'HR',
    description: 'Human Resources Division',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'Operations',
    description: 'Operations and Logistics Division',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Marketing',
    description: 'Marketing and Communications Division',
    createdAt: '2024-01-01T00:00:00Z',
  },
];

export const dummyUsers: User[] = [
  {
    id: '1',
    email: 'admin@arsip.com',
    name: 'Admin User',
    role: 'admin',
    divisionId: '1',
    divisionName: 'IT',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    email: 'staff@arsip.com',
    name: 'Staff User',
    role: 'staff',
    divisionId: '2',
    divisionName: 'Finance',
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '3',
    email: 'operator@arsip.com',
    name: 'Operator User',
    role: 'operator',
    divisionId: '3',
    divisionName: 'HR',
    createdAt: '2024-01-20T00:00:00Z',
  },
  {
    id: '4',
    email: 'staff2@arsip.com',
    name: 'John Doe',
    role: 'staff',
    divisionId: '1',
    divisionName: 'IT',
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: '5',
    email: 'operator2@arsip.com',
    name: 'Jane Smith',
    role: 'operator',
    divisionId: '4',
    divisionName: 'Operations',
    createdAt: '2024-02-10T00:00:00Z',
  },
];

export const dummyArchives: Archive[] = [
  {
    id: '1',
    title: 'IT Infrastructure Report 2024',
    description: 'Annual infrastructure assessment and recommendations',
    fileUrl: '/files/it-report-2024.pdf',
    fileType: 'PDF',
    fileSize: '2.5 MB',
    divisionId: '1',
    divisionName: 'IT',
    uploadedBy: 'Admin User',
    uploadedById: '1',
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
  {
    id: '2',
    title: 'Q1 Financial Statement',
    description: 'First quarter financial performance report',
    fileUrl: '/files/q1-finance.xlsx',
    fileType: 'XLSX',
    fileSize: '1.8 MB',
    divisionId: '2',
    divisionName: 'Finance',
    uploadedBy: 'Staff User',
    uploadedById: '2',
    createdAt: '2024-03-15T00:00:00Z',
    updatedAt: '2024-03-15T00:00:00Z',
  },
  {
    id: '3',
    title: 'Employee Handbook 2024',
    description: 'Updated company policies and procedures',
    fileUrl: '/files/handbook-2024.pdf',
    fileType: 'PDF',
    fileSize: '3.2 MB',
    divisionId: '3',
    divisionName: 'HR',
    uploadedBy: 'Operator User',
    uploadedById: '3',
    createdAt: '2024-02-20T00:00:00Z',
    updatedAt: '2024-02-20T00:00:00Z',
  },
  {
    id: '4',
    title: 'Network Security Audit',
    description: 'Comprehensive security assessment and findings',
    fileUrl: '/files/security-audit.pdf',
    fileType: 'PDF',
    fileSize: '4.1 MB',
    divisionId: '1',
    divisionName: 'IT',
    uploadedBy: 'John Doe',
    uploadedById: '4',
    createdAt: '2024-03-10T00:00:00Z',
    updatedAt: '2024-03-12T00:00:00Z',
  },
  {
    id: '5',
    title: 'Budget Proposal 2025',
    description: 'Detailed budget allocation for next fiscal year',
    fileUrl: '/files/budget-2025.xlsx',
    fileType: 'XLSX',
    fileSize: '2.1 MB',
    divisionId: '2',
    divisionName: 'Finance',
    uploadedBy: 'Staff User',
    uploadedById: '2',
    createdAt: '2024-03-18T00:00:00Z',
    updatedAt: '2024-03-18T00:00:00Z',
  },
  {
    id: '6',
    title: 'Logistics Operations Manual',
    description: 'Standard operating procedures for logistics',
    fileUrl: '/files/ops-manual.pdf',
    fileType: 'PDF',
    fileSize: '5.3 MB',
    divisionId: '4',
    divisionName: 'Operations',
    uploadedBy: 'Jane Smith',
    uploadedById: '5',
    createdAt: '2024-02-25T00:00:00Z',
    updatedAt: '2024-02-25T00:00:00Z',
  },
  {
    id: '7',
    title: 'Recruitment Guidelines',
    description: 'Hiring process and candidate evaluation criteria',
    fileUrl: '/files/recruitment.docx',
    fileType: 'DOCX',
    fileSize: '1.2 MB',
    divisionId: '3',
    divisionName: 'HR',
    uploadedBy: 'Operator User',
    uploadedById: '3',
    createdAt: '2024-03-05T00:00:00Z',
    updatedAt: '2024-03-05T00:00:00Z',
  },
  {
    id: '8',
    title: 'Marketing Campaign Analysis',
    description: 'Q1 campaign performance metrics and insights',
    fileUrl: '/files/marketing-q1.pptx',
    fileType: 'PPTX',
    fileSize: '8.7 MB',
    divisionId: '5',
    divisionName: 'Marketing',
    uploadedBy: 'Admin User',
    uploadedById: '1',
    createdAt: '2024-03-20T00:00:00Z',
    updatedAt: '2024-03-20T00:00:00Z',
  },
];

export const userCredentials = {
  'admin@arsip.com': 'admin123',
  'staff@arsip.com': 'staff123',
  'operator@arsip.com': 'operator123',
};
